nameOverride: ""
fullnameOverride: ""
# -- (dict) Custom deployment annotations
# @section -- Custom deployment values
annotations: {}
# -- (dict) Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
# @section -- Custom deployment values
podTemplateAnnotations: {}
# -- (dict) Deployment labels
# @section -- Custom deployment values
labels: {}
# -- (dict) Deployment strategy
# @section -- Custom deployment values
strategy: {}
# -- (dict) Deployment nodeSelector
# @section -- Custom deployment values
nodeSelector: {}
# -- (dict) Deployment tolerations
# @section -- Custom deployment values
tolerations: []
# -- (dict) Deployment affinity rules
# @section -- Custom deployment values
affinity: {}
# -- (dict) Deployment security context
# @section -- Custom deployment values
securityContext: {}
# dnsPolicy: "None" # Optional dnsPolicy and dnsConfig to put into the Deployment's PodTemplateSpec.
# dnsConfig:
#   nameservers:
#     - 1.1.1.1
# containerSecurityContext: # Optional, plugged in into the both the deployment's main app container and the sidecar.
#   allowPrivilegeEscalation: false


# @section -- Lenses HQ deployment service values
service:
  # -- (bool) Deciding factor whether Lenses HQ service will be created and which type
  # @section -- Lenses HQ deployment service values
  enabled: true

  # -- (string) Type of service to be created.
  # @section -- Lenses HQ deployment service values
  type: ClusterIP

  # -- (dict) Additional service annotations
  # @section -- Lenses HQ deployment service values
  annotations: {}


# -- User to be used by Lenses to deploy apps
# @section -- Permission scope values
serviceAccount:
  # -- (bool) In case "true" new SA will be created with service.name as a SA name.
  # @section -- Permission scope values
  create: false

  # -- (string) Name of Service Account. In case serviceAccount.create is *false*, existing SA with defined name here will be used.
  # @section -- Permission scope values
  name: default

  # -- (dict) Additional service account annotations.
  # @section -- Permission scope values
  annotations: {}


deployment:
  replicas: 1
  #  Resource management
  # -- Pod resources
  # @section -- Custom deployment values
  resources:
    requests:
    #   cpu: 1
      memory: 1Gi
    limits:
    #   cpu: 2
      memory: 1Gi

# -- Image map
# @section -- Custom deployment values
image:
  # -- Image repository
  # @section -- Custom deployment values
  repository: lensting/k2k
  tag: ""

  # -- Default to .Chart.AppVersion
  # tag:
  # -- Image pullPolicy
  # @section -- Custom deployment values
  pullPolicy: IfNotPresent
  # -- imagePullSecrets: # any image pull secrets for private registries go here
  #   - name: regcred

# -- (list) Additional volume mounts to use in Lenses delpoyments, for example to load additional plugins (UDFs) in Lenses
# Use it in conjuction with lenses.additionalVolumes
# @section -- Extras
additionalVolumeMounts: []
  # - name: lenses-plugins
  #   mountPath: "/data/plugins"

# -- (list) Additional volumes to use in Lenses delpoyments either by Lenses for other sidecars like Lenses provisioner.
# @section -- Extras
additionalVolumes: []
  # Example usages:
  #   Lenses: load additional plugins (UDFs) in Lenses
  #   Lenses provisioner: load additional files from pre-existing volumes, secrets or vault secrets to use in provisioning
  # - name: secrets
  #   secret:
  #     secretName: lenses-super-secrets
  # Note: PersistentVolumeClaim should already exist before deploying Helm chart
  # - name: lenses-plugins
  #   persistentVolumeClaim:
  #     claimName: lenses-plugins

k2k:
  license:
    acceptEULA: true
  otelConfig:
    serviceName: "k2k"
    metricsExporter: "prometheus"
    tracesExporter: "none"
    logsExporter: "none"
    prometheusHost: "0.0.0.0"
    prometheusPort: 9090
  replicationConfig: {}
    # (object) Replication configuration for k2k. See documentation for structure.
    # @section -- K2K replication config
    # Example:
    # name: "k2k-demo-env"
    # features:
    #   exactlyOnce: disabled
    #   headerReplication: disabled
    #   schemaMapping: disabled
    #   offsetCommitOptimizePartition: enabled
    #   tracingHeaders: disabled
    #   autoCreateControlTopics: enabled
    #   autoCreateTopics: enabled
    # coordination:
    #   kafka:
    #     assignment:
    #       topic: "__k2k-app-eot-assignment"
    #     commit:
    #       topic: "__k2k-app-eot-consumer-offsets"
    #       group: "k2k.eot"
    # source:
    #   kafka:
    #     consumer:
    #       "group.id": "k2k.eot"
    #     connection:
    #       servers: "source-kafka:9092"
    # target:
    #   kafka:
    #     producer:
    #     connection:
    #       servers: "target-kafka:9092"
    # replication:
    #   - source:
    #       name: source
    #       topic:
    #         - "topic1"
    #         - "topic2"
    #   - sink:
    #       name: sink-source-topic
    #       topic:
    #         prefix: "k2k.eot."
    #       partition: source
  # Additional env variables appended to deployment
  # Follows the format of [EnvVar spec](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  additionalEnv:
    # - name: FOO
    #   value: bar

  livenessProbe:
    # -- (string) Disables livenessProbe, used while debugging
    # @section -- Extras
    enabled: false
