apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k2kApp.fullname" . }}-config
  labels:
    app: {{ include "k2kApp.name" . }}
data:
  config.yaml: |-
{{ .Values.k2k.replicationConfig | toYaml | indent 4 }}
