{{- if .Values.offsetMapper.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "offsetMapper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "offsetMapper.fullname" . }}
    {{- include "commonLabels" . | nindent 4 }}
    lenses.io/app: {{ include "offsetMapper.fullname" . }}
    lenses.io/app.type: k2k-offset-mapper-ns-role
rules:
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: [""]
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups: [""]
  resources:
    - configmaps
    - serviceaccounts
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups: [""]
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - patch
    - watch
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs:
    - create
    - delete
    - scale
    - get
    - list
    - patch
    - update
    - watch
- apiGroups: ["authentication.k8s.io"]
  resources:
    - tokenreviews
  verbs:
    - create
- apiGroups: ["authorization.k8s.io"]
  resources:
    - subjectaccessreviews
  verbs:
    - create

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "offsetMapper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "offsetMapper.fullname" . }}
    {{- include "commonLabels" . | nindent 4 }}
    lenses.io/app: {{ include "offsetMapper.fullname" . }}
    lenses.io/app.type: k2k-offset-mapper-role-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.offsetMapper.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ include "offsetMapper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
