{{- if and .Values.offsetMapper.enabled .Values.offsetMapper.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.offsetMapper.serviceAccount.name }}
{{- if .Values.offsetMapper.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.offsetMapper.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    app: {{ include "offsetMapper.fullname" . }}
    {{- include "commonLabels" . | nindent 4 }}
    lenses.io/app: {{ include "offsetMapper.fullname" . }}
    lenses.io/app.type: k2k-offset-mapper-serviceaccount
{{- end }}
