{{- if .Values.k2k.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k2k.serviceAccount.name }}
{{- if .Values.k2k.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.k2k.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    app: {{ include "fullname" . }}
    {{- include "commonLabels" . | nindent 4 }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: k2k-serviceaccount
{{- end }}
