{{ if .Values.k2k.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    {{- include "commonLabels" . | nindent 4 }}
    component: "k2k"
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: k2k-service
    {{- range $key, $value := .Values.k2k.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if .Values.k2k.service.annotations }}
  annotations:
    {{- toYaml .Values.k2k.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.k2k.service.type | quote }}
  selector:
    app: {{ include "fullname" . | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.k2k.otelConfig.prometheusPort }}
      targetPort: {{ .Values.k2k.otelConfig.prometheusPort }}
      name: metrics
{{- end -}}
